### ISSUE TITLE
Getting "Session goutte is not registered" when using Selenium driver

### ISSUE THREAD

**Issue by MPV** [minkphp/Mink#274]
Hi, 
We've been using Behat v2.3.5 for a while and it's been great! Now we're looking into upgrading to Behat v2.4. 

However there's one thing I can't seem to figure out:

When I run:

```
bin/behat --config tests/acceptance/behat.yml --tags="~@wip&&~@unstable&&@~@manual" 
```

I get:

```
[InvalidArgumentException]           
Session "goutte" is not registered.
```

Using:

composer.json:

```
{
    "require": {
        "php": ">=5.3.8",
        "behat/behat": "2.4@stable",
        "behat/mink": "1.4@stable",
        "behat/mink-extension": "*",
        "behat/mink-selenium-driver": "*",
        "behat/mink-selenium2-driver": "*"
    },
    "config": {
        "bin-dir": "bin/"
    }
}
```

behat.yml:

```
default:
  paths:
    features: '%behat.paths.base%/features/'
    bootstrap: '%behat.paths.base%/context/'
  formatter:
    parameters:
      language: 'en'
  context:
    parameters:
      default_session: selenium
      javascript_session: selenium

      # Default selenium server
      selenium:
        host: localhost
        port: 4444
  extensions:
    Behat\MinkExtension\Extension:
      selenium: ~
```
