### ISSUE TITLE
Default browser window size in configuration

### ISSUE THREAD

**Issue by gonzalovilaseca** [minkphp/Mink#525]
It would be great to have a default browser window size that can be defined in configuration, otherwise I have to add an extra step in every Behat scenario of the kind:
`'And I set browser window size to "1024" x "768"'`

**Comment by pscheit** [comment]
```
default:
  suites:
    something:
      paths: ...
      mink_javascript_session: selenium1280


 extensions:
    BehatTests\MinkExtension:
      base_url:  'https://set-from-env-look-at-BehatTests\\MinkExtension'

      sessions:
        selenium:
          selenium2:
            browser: chrome
            wd_host: "host.docker.internal:4444/wd/hub"

        selenium1280:
          selenium2:
            browser: chrome
            wd_host: "host.docker.internal:4444/wd/hub"
            capabilities:
              chrome:
                switches: ["--window-size=1280,900"]

```

**Comment by pscheit** [comment]
for the newer selenium2driver this does not work anymore - its missing prefs. We need to workaround that part:

in your selenium server you get this error:
```
from invalid argument: cannot parse capability: goog:chromeOptions
from invalid argument: cannot parse prefs
from invalid argument: must be a dictionary
```

workaround in behat.yaml
```
        selenium1280:
          selenium2:
            browser: chrome
            wd_host: "host.docker.internal:4444/wd/hub"
            capabilities:
              chrome:
                switches: ["window-size=1280,900"]
                prefs:
                  intl:
````

(just create anything under prefs, that would require prefs to be an associative array)
