### ISSUE TITLE
Wrong file name when i upload file through Behat/Mink

### ISSUE THREAD

**Issue by molchanoviv** [minkphp/Mink#604]
Hello guys. I have such a test

```
  Scenario: Upload file
    Given I set basic authentication with "marketing" and "*********"
    And I have content in the "product" database table:
      | id | slug           | name           | description    | enabled | created_at          | updated_at          | css_guide_lines |
      | -3 | behat product3 | behat product3 | behat product3 | true    | 2014-04-04 11:27:27 | 2014-04-04 11:27:27 | false           |
    And I go to "/utils/renderer-guides/product/-3"
    And I attach the file "features/fixtures/files/renderer-guides.txt" to "renderer_guide_form_file"
    And I press "Upload"
    Then the response status code should be 200
    And I should see "Updated guide file for product behat product3."
    And I should see "renderer-guides.txt"
    Then I go to "/utils/renderer-guides/product/-3/delete"
```

And such a config file

``` yaml
default:
  suites:
    default:
      paths:
        - %paths.base%/features
      contexts:
        - behatch:browser
        - behatch:debug
        - behatch:system
        - behatch:json
        - behatch:table
        - Opensoft\Onp\Features\Context\FeatureContext
        - Opensoft\CommonContext\WebContext
        - Opensoft\CommonContext\XmlContext
        - Opensoft\Onp\Features\Context\RabbitMQContext
        - Opensoft\Onp\Features\Context\RestContext
    critical:
      paths:
        - %paths.base%/features
      contexts:
        - behatch:browser
        - behatch:debug
        - behatch:system
        - behatch:json
        - behatch:table
        - Opensoft\Onp\Features\Context\FeatureContext
        - Opensoft\CommonContext\WebContext
        - Opensoft\CommonContext\XmlContext
        - Opensoft\Onp\Features\Context\RabbitMQContext
        - Opensoft\Onp\Features\Context\RestContext
      filters:
          tags: "@critical"
  extensions:
    Behat\Symfony2Extension: ~
    Behat\MinkExtension:
      sessions:
        symfony2:
          goutte:
            guzzle_parameters:
              curl.options:
                CURLOPT_SSL_VERIFYPEER: false
                CURLOPT_CERTINFO: false
                CURLOPT_SSL_VERIFYHOST: false
                CURLOPT_SSLVERSION: 3
                CURLOPT_SSL_CIPHER_LIST: SSLv3
              ssl.certificate_authority: false
        selenium:
          selenium2: ~
      base_url: 'http://onp.dev'
      goutte: ~
      selenium2: ~
      javascript_session: selenium2
      default_session: symfony2
      show_cmd: 'firefox %s'
    Sanpi\Behatch\Extension: ~
```

When I run this test it fails at the step `And I should see "renderer-guides.txt"` because the file name is changed to some_hash.txt (where some_hash is an unknown hash). But if if i try to reproduce this test manually in browser it works ok. File name is correct. The same if i try to test it manually through curl

``` sh
curl -k -i -sslv3 --user marketing:********* -X POST -F renderer_guide_form[file]=@features/fixtures/files/renderer-guides.txt https://onp.dev/app_test.php/utils/renderer-guides/product/-3/add
```

File name is changed only if i run test in behat. Why this could happen?
