### ISSUE TITLE
MinkContext - it is not an interface

### ISSUE THREAD

**Issue by vhgomo** [minkphp/Mink#756]
Im implementing behat on symfony 3.4 with mink, i already create the following behat.yml:
```
default:
  extensions:
    Behat\Symfony2Extension: ~
    Behat\MinkExtension:
     goutte: ~
     selenium2: ~
     base_url: http://mastersymfony.dev/app_dev.php
```
but when i run behat on cmd i get:

```
In FeatureContext.php line 12:

  Error: FeatureContext cannot implement Behat\MinkExtension\Context\MinkContext - it is not an interface
```

Any idea of what could be going wrong?
