### ISSUE TITLE
New release for providing Symfony 4 support

### ISSUE THREAD

**Issue by adiq** [minkphp/Mink#757]
It would be great to release new version of Mink to provide Symfony 4 support.

**Comment by pamil** [comment]
Is there anything that needs to be done to tag a new release?

**Comment by adiq** [comment]
I think there is nothing to do, as 808702de1a3bebbd97a9339790e313e2aa7525ee fixes the dependencies problem. I'll try to test it on real project and will let you know.

**Comment by stof** [comment]
Well, before making new releases for Mink packages, I would like to make CI green for the different drivers (IIRC, the Selenium2Driver CI has issues currently)

**Comment by kochen** [comment]
@adiq did you manage to get Sessions to work?

I'm getting:
```
Specify session name to get
```
See: https://github.com/Behat/MinkExtension/issues/321

and is `$sessions` (https://github.com/minkphp/Mink/blob/master/src/Mink.php#L36) is actually empty... :/

**Comment by bartonhammond** [comment]
I'm getting same error ` Specify session name to get (InvalidArgumentException)` .  Any update?

**Comment by adiq** [comment]
I will look into this when I will have some spare time. Did you tried to revert mentioned commit and see if the issue persists?

**Comment by bartonhammond** [comment]
I got past that error by adding the line below

```
default:
  suites:
    default:
      paths: ["%paths.base%/features/temp/home.feature"]
      local_screenshots: false      
      contexts: [ThinkWellContext]

  extensions:
    Behat\MinkExtension:
      browser_name: 'chrome'
      base_url: https://twlw.wpengine.com      
      default_session: cross_browser_testing  #### Added this line
      cross_browser_testing:
```
